import type { Metadata } from 'next';
import { Inter, Lobster } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const lobster = Lobster({
  subsets: ['latin'],
  variable: '--font-lobster',
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Next.js Task',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${inter.variable} ${lobster.variable}`}>
        {children}
      </body>
    </html>
  );
}
